name: paisa_split
description: Offline-first shared expense app with personal financial journal
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^12.1.3
  
  # Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Security
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.6
  cryptography: ^2.5.0
  
  # Notifications & Background
  flutter_local_notifications: ^16.3.0
  workmanager: ^0.5.2
  
  # File Operations
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  
  # UI & Charts
  fl_chart: ^0.65.0
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.18.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  freezed: ^2.4.6

  # Assets Generation
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

  # Testing
  mocktail: ^1.0.2
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/logo.svg
    - assets/icons/logo.png

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 24
  adaptive_icon_background: "#99F6E4"
  adaptive_icon_foreground: "assets/icons/logo.png"

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#99F6E4"
  color_dark: "#134E4A"
  image: assets/icons/logo.png
  android_12:
    image: assets/icons/logo.png
    color: "#99F6E4"
    color_dark: "#134E4A"
